---
title: "Alternative Fuel Stations"
output: html_document
author: Saatvik Kher
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(showtext)
library(tidytuesdayR)
library(tidyverse)
library(ggplot2)
library(patchwork)
library(mosaic)
library(broom)
library(janitor)

tuesdata <- tidytuesdayR::tt_load('2022-03-01')
stations <- tuesdata$stations
rm(tuesdata)
```

```{r}
us_states <- tibble(
  state_name = state.name,
  state_abb = state.abb)

stations <- stations %>%
  janitor::clean_names()

stations <- stations %>% 
  filter(fuel_type_code == "ELEC",
         status_code == "E") %>% 
  count(state) %>% 
  rename(state_abb = state, total = n) %>% 
  left_join(us_states) %>%
  mutate(state_name = tolower(state_name)) %>% 
  select(state_name, total) %>% 
  mutate(bin = case_when(total <= 1000 ~ "0-1000",
                         total > 1000 & total <= 2000 ~ "1000-2000",
                         total > 2000 & total <= 3000 ~ "2000-3000",
                         total > 3000 ~ "3000+"))
```

```{r}
us_elec_stations <- map_data("state") %>% 
  left_join(stations, by = c("region" = "state_name"))

us_map <- ggplot(data = us_elec_stations,
       mapping = aes(x = long, y = lat, group = group,
                     fill = bin)) +
  geom_polygon(colour = "black") +
  ggtitle("Electric car charging stations in the U.S.") +
  guides(fill=guide_legend(title="Count"))
us_map
```

```{r}

ggsave("Electric car charging stations.png", us_map, dpi = 320, width = 12, height = 6)
```

