---
title: "Alternative Fuel Stations"
output: html_document
author: Saatvik Kher
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(showtext)
library(tidytuesdayR)
library(tidyverse)
library(ggplot2)
library(patchwork)
library(mosaic)
library(broom)
library(janitor)
library(plotly)

tuesdata <- tidytuesdayR::tt_load('2022-03-01')
stations <- tuesdata$stations
rm(tuesdata)
```


```{r}
latlong <- stations %>% select(LATITUDE, LONGITUDE, FUEL_TYPE_CODE)

latlong %>% count(FUEL_TYPE_CODE)

geo_properties = list(
  scope = "usa",
  projection = list(type = "albers usa"),
  showland = TRUE,
  showsubunits = TRUE,
  landcolor = toRGB("gray10"),
  showlakes = TRUE,
  lakecolor = toRGB("white")
)

stations_graph = plot_geo(latlong,
                          lat = ~LATITUDE,
                          lon = ~LONGITUDE,
                          marker = list(size = 2, color = "#93E778", opacity = 0.25)) %>%
  add_markers(hoverinfo = "none") %>%
  config(displayModeBar = FALSE) %>%
  layout(geo = geo_properties)
                          

stations_graph %>% save_image("alternativefuelstation.png")
 
```
