---
title: "Droughts"
author: "Saatvik Kher"
date: '2022-06-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(broom)
library(ggplot2)
library(fable)
library(lubridate)
library(sweep)
library(forecast)
library(timetk)
library(tidyquant)

theme_set(theme_light())
```


```{r}
# Data Import

drought <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-14/drought.csv')
drought_fips <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-14/drought-fips.csv')
```


```{r}
drought_fips %>% 
  filter(State == "CA") %>%
  arrange(date) %>%
  filter(FIPS %in% c("06085", "06081", "06083")) %>%
  ggplot(aes(date, DSCI, colour = FIPS)) +
  geom_line()
```

# Going to try some time series forecasting 

Learning from https://bookdown.org/mpfoley1973/time-series/ 

```{r}
drought_fips %>%
  filter(State == "CA") %>%
  arrange(date) %>%
  filter(FIPS == "06037") %>%
  select(DSCI) %>%
  ts.plot()
```


```{r}
drought_fips %>% 
  group_by(State) %>%
  summarise(DSCI = mean(DSCI)) %>%
  mutate(State = fct_reorder(State, DSCI)) %>%
  head(10) %>%
  ggplot(aes(x = State, y = DSCI)) +
  geom_col() +
  coord_flip()
```


```{r}
drought_fips %>%
  mutate(month = month(date, label = TRUE), year = year(date), quarter = quarter(date), dst = dst(date))
```


# Going to forecast for LA County, CA

```{r}
LA <- drought_fips %>%
  filter(FIPS == "06037") %>%
  mutate(month = month(date, label = TRUE), year = year(date), quarter = quarter(date), dst = dst(date))

LA %>% group_by(year, month) %>%
  summarise(DSCI = mean(DSCI)) %>%
  ggplot(aes(x = month, y = DSCI, group = year)) +
    geom_line(aes(color = year)) +
    labs(title = "Average monthly DSCI", x = "", y = "Average DSCI") +
    scale_y_continuous()

```
```{r}
LA %>% mutate(`5year` = cut(year, breaks = c(1900, 2005, 2010, 2015, 2025), labels = c("2000 - 2005", "2005 - 2010", "2010 - 2015", "2015 - 2022"))) %>%
  group_by(`5year`, month) %>%
  summarise(DSCI = mean(DSCI)) %>%
  ggplot(aes(x = month, y = DSCI, group = `5year`)) +
    geom_line(aes(color = `5year`)) +
    labs(title = "Average monthly DSCI", x = "", y = "Average DSCI")
```

```{r}
LA_ts <- LA %>% select(date, DSCI) %>%
  mutate(date = floor_date(date, unit = "week")) %>%
  tk_ts(start = 2000, freq = 365.25/7, silent = TRUE)

LA_ts %>% sw_tidy() %>%
  ggplot(aes(x = index, y = value)) +
  geom_line()
```


```{r}
fit_ets <- LA_ts %>%
    ets()

fit_ets %>% sw_tidy()

decomp_fit_ets <- sw_tidy_decomp(fit_ets)
decomp_fit_ets

```

```{r}
decomp_fit_ets %>%
    gather(key = key, value = value, -index) %>%
    mutate(key = forcats::as_factor(key)) %>%
    ggplot(aes(x = index, y = value, group = key)) +
    geom_line(color = palette_light()[[2]]) +
    geom_ma(ma_fun = SMA, n = 12, size = 1) +
    facet_wrap(~ key, scales = "free_y") +
    scale_x_yearmon(n = 10) +
    labs(title = "US Alcohol Sales: ETS Decomposition", x = "") +
    theme_tq() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
fit_stl <- LA_ts %>%
    stlf(robust=TRUE)

fit_stl

fit_stl %>% forecast(method = "naive") %>%
  autoplot()
```


# Grouping by Month

```{r}
LA_m <- LA %>% 
  mutate(date = floor_date(date, "month")) %>%
  group_by(date) %>%
  summarise(DSCI = mean(DSCI)) %>%
  mutate(month = month(date), quarter = quarter(date))

LA_ts <- LA_m %>% select(date, DSCI) %>% tk_ts(start = 2000, freq = 12, silent = TRUE)
  
fit_ets <- LA_ts %>%
  ets()

fit_ets %>% sw_tidy()
```


```{r}
augment_fit_ets <- sw_augment(fit_ets)

augment_fit_ets %>%
    ggplot(aes(x = index, y = .resid)) +
    geom_hline(yintercept = 0, color = "grey40") +
    geom_point(color = palette_light()[[1]], alpha = 0.5) +
    geom_smooth(method = "loess") +
    scale_x_yearmon(n = 10) +
    labs(title = "LA County Droughts: ETS Residual", x = "") +
  theme_tq()
```

```{r}
decomp_fit_ets <- sw_tidy_decomp(fit_ets)

decomp_fit_ets %>%
    gather(key = key, value = value, -index) %>%
    mutate(key = forcats::as_factor(key)) %>%
    ggplot(aes(x = index, y = value, group = key)) +
    geom_line(color = palette_light()[[2]]) +
    geom_ma(ma_fun = SMA, n = 12, size = 1) +
    facet_wrap(~ key, scales = "free_y") +
    scale_x_yearmon(n = 10) +
    labs(title = "LA County Droughts: ETS Decomposition", x = "") +
    theme_tq() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
fcast_ets <- fit_ets %>%
    forecast(h = 12)

sw_sweep(fcast_ets, fitted = TRUE)
```

```{r}
sw_sweep(fcast_ets) %>%
    ggplot(aes(x = index, y = DSCI, color = key)) +
    geom_ribbon(aes(ymin = lo.95, ymax = hi.95),
                fill = "#D5DBFF", color = NA, size = 0) +
    geom_ribbon(aes(ymin = lo.80, ymax = hi.80, fill = key),
                fill = "#596DD5", color = NA, size = 0, alpha = 0.8) +
    geom_line(size = 1) +
    labs(title = "LA County Droughts, ETS Model Forecast", x = "", y = "DSCI",
         subtitle = "Regular Time Index") +
    scale_x_yearmon(n = 12, format = "%Y") +
    scale_color_tq() +
    scale_fill_tq() +
    theme_tq()
```

# Predict 2020 - 2022?

```{r}
LA_m %>% head(250) %>%
  select(date, DSCI) %>% 
  tk_ts(start = 2000, freq = 12, silent = TRUE) %>% 
  forecast(h = 12) %>% 
  sw_sweep() %>%
  ggplot(aes(x = index, y = DSCI, color = key)) +
    geom_ribbon(aes(ymin = lo.95, ymax = hi.95),
                fill = "#D5DBFF", color = NA, size = 0) +
    geom_ribbon(aes(ymin = lo.80, ymax = hi.80, fill = key),
                fill = "#596DD5", color = NA, size = 0, alpha = 0.8) +
    geom_line(size = 1) +
    labs(title = "LA County Droughts, ETS Model Forecast", x = "", y = "DSCI",
         subtitle = "Regular Time Index") +
    scale_x_yearmon(n = 12, format = "%Y") +
    scale_color_tq() +
    scale_fill_tq() +
    theme_tq()
```

